language: node_js
sudo: false
node_js:
  - 10
install:
  - yarn install
addons:
  postgresql: "9.6"
services:
  - postgresql
env:
  - NODE_ENV=travis
before_script:
  - psql -c 'create database podcloud_stats_test;' -U postgres
  - NODE_ENV=travis npm run db-migrate up
script:
  - NODE_ENV=travis yarn codecov
before_deploy:
  - openssl aes-256-cbc -K $encrypted_17c9c2b55791_key -iv $encrypted_17c9c2b55791_iv
    -in .deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  - provider: script
    script: "./deploy.sh preprod"
    on:
      branch: develop
  - provider: script
    script: "./deploy.sh production"
    on:
      branch: master
