version: '3'
services:
  db:
    image: cassandra
  server:
    image: node:carbon
    working_dir: /app
    volumes: 
      - ./:/app
    ports:
      - "3000:3000"
    command: "npm run nodemon"
    depends_on:
      - db
